name: simple_rich_text
description: Display a Dart string in Flutter using simple rich text characters.
version: 1.0.35        #NOEDIT
homepage: https://github.com/remoteportal/simple_rich_text

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  url_launcher: ^5.1.2
  simple_navigation:
    git:
      url: https://github.com/remoteportal/simple_navigation.git
      ref: 13c18bc

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
